config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: { registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:edit,:update,:index] do
    member do
      get 'messages'
    end
  end

  resources :messages do
    collection do
      get 'sent'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/messages/sent' => 'messages#sent'
      resources :messages, only: [:index, :show, :create]
      get '/profile' => 'users#profile'
      patch '/profile' => 'users#update'
    end
  end

  get '/archived' => 'messages#archived', as: 'archived'
  patch '/archive' => 'messages#archive', as: 'archive', defaults: {format: 'js'}
  patch '/archive_multiple' => 'messages#archive_multiple', as: 'archive_multiple', defaults: {format: 'js'}
end

app/models/message.rb
class Message < ApplicationRecord
  before_update :update_tracker
  validates_presence_of :title, :content, :from, :to

  enum status: { unread: 0, read: 1, archived: 2 }

  belongs_to :sender, class_name: 'User', foreign_key: 'from'
  belongs_to :receiver, class_name: 'User', foreign_key: 'to'

  delegate :name, :email, to: :sender, prefix: true
  delegate :name, to: :receiver, prefix: true

  scope :sent_to, ->(user) { includes(:sender).where(to: user.id).where.not(status: 2) }
  scope :sent_from, ->(user) { includes(:receiver).where(from: user.id).where.not(status: 2) }
  scope :all_sent_to, ->(user) { where(to: user.id) }
  scope :ordered, -> { order('created_at DESC') }
  scope :master_messages, -> { includes(:sender).where.not(status: 2) }
  attr_accessor :receiver_email

  # callback on update
  def update_tracker
    return unless status_changed?

    if read? && status_was == 'unread' # only update visualized if status change from unread
      self.visualized = Time.now
    elsif archived? && status_was != 'archived' # only update archived if status wasn't already archived
      self.archived = Time.now
    end
  end
end

app/controllers/api/v1/messages_controller.rb
module Api::V1
  class MessagesController < ApiController
    def index
      if @current_user.permission == 'master'
        render json: Message.master_messages
      else
        render json: @current_user.messages
      end
    end

    def show
      message = Message.find(params[:id])
      if @current_user.permission != 'master'
        return unless @current_user == message.receiver

      end
      render json: message
    end

    def create
      user = User.find_by_email(message_params[:receiver_email])
      message = Message.new(message_params.merge(from: @current_user.id))
      message.to = user.id if user

      if message.save
        render json: message
      else
        render json: message.errors
      end
    end

    def sent
      messages = if @current_user.permission == 'master'
                   Message.ordered
                 else
                   Message.sent_from(@current_user).ordered
                 end
      render json: messages
    end

    private

    def message_params
      params.require(:message).permit(
        :title,
        :content,
        :receiver_email,
        :to
      )
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  load_and_authorize_resource # cancancan permissions
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token
  before_action :verify_author, only: [:show]
  # render form for new message

  def new
    @message = Message.new
  end

  # creates a new message
  def create
    user = User.find_by_email(message_params[:receiver_email]) # find user by email instead of id
    @message = Message.new(message_params.merge(from: current_user.id)) # adds current_user id as sender of the message
    @message.to = user.id if user # if user is not found , message is rejected

    if @message.save
      redirect_to messages_path, notice: 'Mensagem enviada com sucesso.'
    else
      redirect_to new_message_path, flash: { danger: 'Houve um erro' }
    end
  end

  # index checks if user has master permission
  def index
    @messages = current_user.master? ? Message.master_messages.ordered : Message.sent_to(current_user).ordered
  end

  # shows content of the message
  def show
    @message = Message.find(params[:id])
    return unless @message.unread? && current_user == @message.receiver

    @message.read!
    # only set to read if current_user is the receiver of the message
  end

  # archive a single message by id
  def archive
    @message = Message.find_by_title(params[:title])
    @message.archived!

    respond_to do |format|
      format.js
    end
  end

  # achive multiples messages by sending multiple ids
  def archive_multiple
    messages = Message.find(params[:messages_ids])
    messages.each(&:archived!)

    respond_to do |format|
      format.js
    end
  end

  # get all messages that current_user sent
  def sent
    @messages = Message.sent_from(current_user).ordered
  end

  # get all archived messages from the application
  def archived
    @messages = Message.includes(:sender).archived.ordered
  end

  private

  def message_params
    params.require(:message).permit(
      :title,
      :content,
      :receiver_email,
      :to
    )
  end

  def verify_author
    message = Message.find(params[:id])
    return if ([message.receiver, message.sender].include?(current_user) && !message.archived?) || current_user.master?

    redirect_to messages_path
  end
end

app/views/messages/archive_multiple.js.erb
$.each($('.messages_ids:checkbox:checked'),function(){
  $(this).parent().parent().remove()
  var count = 0;
  if ($(this).parent().parent().hasClass('unread')){
    count = count + 1;
  }
  $('.content').first().data('unread',$('.content').first().data('unread') - count)
  $('#unread_messages').text('Mensagens (' + $('.content').first().data('unread') + ')')

  $('.content').first().data('archived',$('.content').first().data('archived') + 1)
  $('#archived_messages').text('Mensagens (' + $('.content').first().data('archived') + ')')
});

app/views/messages/archived.html.slim
.container-fluid
  .row
    .col-md-12
      .card
        = form_tag archive_multiple_path, method: :patch, remote: true do
          .header
            h4.title Caixa de Entrada
            span.message_date
          .content.table-responsive.table-full-width
            table.table
              thead
                th
                th
                th
              tbody
                - @messages.each do |message|
                  tr.clickable class="#{'unread' if message.unread?}"
                    td #{message.sender_name}
                    td.message_content
                      = link_to message.title, message_path(message), class: 'view_message'
                    td #{message_date(message)}

app/views/messages/index.html.slim
.container-fluid
  .row
    .col-md-12
      .card
        = form_tag archive_multiple_path, method: :patch, remote: true do
          .header
            h4.title Caixa de Entrada
            span.message_date
              = button_tag(type: 'submit', class: 'btn btn-default') do
                span Excluir Selecionadas
                i.fa.fa-2x.fa-trash
          .content.table-responsive.table-full-width
            table.table
              thead
                th
                th
                th
                th
                th
              tbody
                - @messages.each do |message|
                  tr.clickable class="#{'unread' if message.unread?}"
                    td.not_clickable #{check_box_tag 'messages_ids[]',message.id, false, class: 'messages_ids not_clickable'}
                    td #{message.sender_name}
                    td.message_content
                      = link_to message.title, message_path(message), class: 'view_message'
                    td #{message_date(message)}
                    td.not_clickable
                      = button_tag(type: 'button',class: 'btn btn-default btn-xs single_archive not_clickable',id: 'delete_message') do
                        i.fa.fa-2x.fa-trash.not_clickable

app/views/messages/new.html.slim
.container-fluid
  .row
    .col-lg-10.col-lg-offset-1.col-md-7.col-md-offset-4
      .card
        .header
          h4.title AgendaMail
          p.category Escreva a mensagem.
        .content.table-responsive.table-full-width
          = form_for @message do |f|
            .row
              .col-md-11
                .form-group.login_input
                  = f.label 'Para:'
                  = f.text_field :receiver_email, class: 'form-control border-input', placeholder: 'Email', required: true
            .row
              .col-md-11
                .form-group.login_input
                  = f.label 'Assunto'
                  = f.text_field :title, class: 'form-control border-input', placeholder: 'Assunto', required: true
            .row
              .col-md-11
                .form-group.login_input
                  = f.label 'Conteúdo'
                  = f.text_area :content, class: 'form-control border-input', required: true


            .text-center
              button.btn.btn-info.btn-fill.btn-wd type="submit"  Enviar

app/views/messages/sent.html.slim
.container-fluid
  .row
    .col-md-12
      .card
        .header
          h4.title Caixa de Entrada
          span.message_date
        .content.table-responsive.table-full-width
          table.table
            thead
              th
              th
              th
            tbody
              - @messages.each do |message|
                tr.clickable class="#{'unread' if message.unread?}"
                  td #{message.receiver_name}
                  td.message_content
                    = link_to message.title, message_path(message), class: 'view_message'
                  td #{message_date(message)}

app/views/messages/show.html.slim
.container-fluid
  .row
    .col-md-12
      .card
        .header
          h4.title #{@message.title}
          /p.category Here is a subtitle for this table
        .content
          span Mensagem de: #{@message.sender_email}
          br
          span Mensagem para: #{@message.receiver.email}
          span.message_date #{@message.created_at.strftime("%d/%m/%Y")} | #{@message.created_at.to_s(:time)}
          - if @message.archived?
            br
            span.message_date.red Mensagem Arquivada no dia #{@message.archived.strftime("%d/%m/%Y")}
          hr
          p.message_content #{@message.content}