config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: { registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:edit,:update,:index] do
    member do
      get 'messages'
    end
  end

  resources :messages do
    collection do
      get 'sent'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/messages/sent' => 'messages#sent'
      resources :messages, only: [:index, :show, :create]
      get '/profile' => 'users#profile'
      patch '/profile' => 'users#update'
    end
  end

  get '/archived' => 'messages#archived', as: 'archived'
  patch '/archive' => 'messages#archive', as: 'archive', defaults: {format: 'js'}
  patch '/archive_multiple' => 'messages#archive_multiple', as: 'archive_multiple', defaults: {format: 'js'}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable

  validates_presence_of :name

  enum permission: { normal: 0, master: 1 }
  before_create :create_token

  has_many :messages, foreign_key: 'to'

  # get all sent messages from user
  def messages_sent
    Message.sent_from(self)
  end

  protected

  # callback to create api token when user is created
  def create_token
    self.token = name.first(4).upcase + Time.now.strftime('%H:%M:%S').strip.to_s.gsub(/[^\d]/, '') unless token
  end
end

app/controllers/api/v1/users_controller.rb
module Api::V1
  class UsersController < ApiController
    def profile
      render json: @current_user
    end

    def update
      if user_params[:password].blank? || user_params[:password_confirmation].blank?
        params[:user].delete(:password)
        params[:user].delete(:password_confirmation)
      end

      if @current_user.update(user_params)
        render json: @current_user
      else
        render json: @current_user.errors
      end
    end

    private

    def user_params
      params.require(:user).permit(
        :name,
        :email,
        :password,
        :password_confirmation
      )
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[
                                        name
                                        password
                                        email
                                      ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource # cancancan permissions
  before_action :authenticate_user!
  before_action :set_user, except: [:index]

  # render edit form
  def edit; end

  # update user info
  def update
    if user_params[:password].blank? || user_params[:password_confirmation].blank?
      params[:user].delete(:password)
      params[:user].delete(:password_confirmation)
    end

    if @user.update(user_params)
      bypass_sign_in(@user) # if user change password sign_in user again
      redirect_to messages_path, notice: 'Perfil editado com sucesso.'
    else
      redirect_to edit_user_path(id: @user.id), flash: { danger: 'Houve um erro.' }
    end
  end

  # get all non archived messages
  def index
    @users = User.normal
  end

  # get all messages non archived of a user , sent and received
  def messages
    @user = User.find(params[:id])
    @sent = Message.sent_from(@user).ordered
    @received = Message.sent_to(@user).ordered
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/views/users/edit.html.slim
.container-fluid
  .row
    .col-lg-5.col-lg-offset-3.col-md-7.col-md-offset-4
      .card
        .header
          h4.title AgendaMail
          p.category Edite seu perfil.
        .content.table-responsive.table-full-width
          = form_for @user do |f|
            .row
              .col-md-11
                .form-group.login_input
                  = f.label 'Nome'
                  = f.text_field :name, class: 'form-control border-input', placeholder: 'Nome'
            .row
              .col-md-11
                .form-group.login_input
                  = f.label :email
                  = f.text_field :email, class: 'form-control border-input', placeholder: 'Email'
            .row
              .col-md-11
                .form-group.login_input
                  = f.label 'Senha'
                  - if @minimum_password_length
                    em
                      | (minímo de #{@minimum_password_length} caracteres)
                  br/
                  = f.password_field :password, class: 'form-control border-input', placeholder: 'Senha'

            .row
              .col-md-11
                .form-group.login_input
                  = f.label 'Confirmação de senha'
                  = f.password_field :password_confirmation, class: 'form-control border-input', placeholder: 'Senha'

            .text-center
              button.btn.btn-info.btn-fill.btn-wd type="submit"  Editar Perfil
    - unless current_user.master?
      .col-lg-3.col-md-3
        .card
          .header
            h4.title Token Para API
            span#see_token Ver
            p.category#token #{current_user.try(:token)}

app/views/users/index.html.slim
.container-fluid
  .row
    .col-md-12
      .card
        .header
          h4.title Caixa de Entrada
        .content.table-responsive.table-full-width
          table.table
            thead
              th
              th
            tbody
              - @users.each do |user|
                tr.clickable_user data-href="#{messages_user_path(user)}"
                  td #{link_to user.name, messages_user_path(user)}
                  td #{user.email}

app/views/users/messages.html.slim
.container-fluid
  .row
    .col-lg-6.col-md-6
      .card
        .header
          h4.title Recebidas
        .content.table-responsive.table-full-width
          table.table
            thead
              th
              th
              th
            tbody
              - @received.each do |message|
                tr.clickable class="#{'unread' if message.unread?}"
                  td #{message.sender_name}
                  td.message_content
                    = link_to message.title, message_path(message), class: 'view_message'
                  td #{message_date(message)}

    .col-lg-6.col-md-6
      .card
        .header
          h4.title Enviadas
        .content.table-responsive.table-full-width
          table.table
            thead
              th
              th
              th
            tbody
              - @sent.each do |message|
                tr.clickable class="#{'unread' if message.unread?}"
                  td #{message.sender_name}
                  td.message_content
                    = link_to message.title, message_path(message), class: 'view_message'
                  td #{message_date(message)}