config/routes.rb
Rails.application.routes.draw do
  devise_for :users , controllers: { registrations: 'users/registrations'}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  resources :users, only: [:edit,:update,:index] do
    member do
      get 'messages'
    end
  end

  resources :messages do
    collection do
      get 'sent'
    end
  end

  namespace :api do
    namespace :v1 do
      get '/messages/sent' => 'messages#sent'
      resources :messages, only: [:index, :show, :create]
      get '/profile' => 'users#profile'
      patch '/profile' => 'users#update'
    end
  end

  get '/archived' => 'messages#archived', as: 'archived'
  patch '/archive' => 'messages#archive', as: 'archive', defaults: {format: 'js'}
  patch '/archive_multiple' => 'messages#archive_multiple', as: 'archive_multiple', defaults: {format: 'js'}
end

app/views/layouts/_footer.html.slim
footer.footer
    .container-fluid
      nav.pull-left
        ul
          li
            a href="http://www.creative-tim.com" Creative Tim
          li
            a href="http://blog.creative-tim.com" Blog
          li
            a href="http://www.creative-tim.com/license" Licenses
      .copyright.pull-right

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String) && !msg.blank?
      - if name.to_s == 'notice'
        javascript:
          $.notify({
            // options
            message: "#{msg}"
          },{
            // settings
            type: 'success',
            placement: {
             from: 'top',
             align: 'center'
            }
          });
      - else
        javascript:
          $.notify({
            // options
            message: "#{msg}"
          },{
            // settings
            type: 'danger',
            placement: {
             from: 'top',
             align: 'center'
            }
          });

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-default
  .container-fluid
    .navbar-header
      button.navbar-toggle type="button"
        span.sr-only Toggle navigation
        span.icon-bar.bar1
        span.icon-bar.bar2
        span.icon-bar.bar3
      a.navbar-brand href="#"  Mensagens
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li.dropdown
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.fa.fa-gear
            p Opções
            b.caret
          ul.dropdown-menu
            li
              = link_to 'Perfil', edit_user_path(current_user)
            li
              = link_to 'Sair', destroy_user_session_path, method: :delete

app/views/layouts/_sidebar.html.slim
.sidebar data-active-color="danger" data-background-color="white"
  .sidebar-wrapper
    .logo
      a.simple-text href="/messages"
        | AgendaMail
      span #{current_user.name}
    ul.nav
      - unless current_user.master?
        li class="#{ active?(new_message_path)} hide_sidebar"
          a href="/messages/new"
            i.fa.fa-pencil
            p Escrever
        li class="#{ active?(sent_messages_path)} hide_sidebar"
          a href="/messages/sent"
            i.fa.fa-envelope-open
            p Enviadas (#{current_user.messages_sent.size})
      li class="#{ active?(messages_path)} hide_sidebar"
        a href="/messages"
          i.fa.fa-envelope-o
          p#unread_messages Mensagens (#{user_messages})
      - if current_user.master?
        li class="#{ active?(archived_path)} hide_sidebar"
          a href="/archived"
            i.fa.fa-archive
            p#archived_messages Arquivadas (#{archived_count})
        li class="#{ active?(users_path)} hide_sidebar"
          a href="/users"
            i.fa.fa-user
            p Usuários (#{users_count})

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" /
    meta content="width=device-width" name="viewport" /
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    title AgendaMail
    = csrf_meta_tags


    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Muli:400,300"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'


  body
    .wrapper
        = render 'layouts/sidebar'
        .main-panel
            = render 'layouts/messages'
            = render 'layouts/navbar'
            .content data-unread="#{user_messages}" data-archived="#{archived_count}"
                = yield
            = render 'layouts/footer'

app/views/layouts/login.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" name="viewport" /
    meta content="width=device-width" name="viewport" /
    meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    title AgendaMail
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

    = stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css"
    = stylesheet_link_tag "https://fonts.googleapis.com/css?family=Muli:400,300"



  body
    .wrapper
        .main-panel style='width:100%;'
            = render 'layouts/messages'
            = yield
            = render 'layouts/footer'